import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <title>LIGHTUP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.cdnfonts.com/css/hind" rel="stylesheet" />
        <link href="https://fonts.cdnfonts.com/css/manrope" rel="stylesheet" />
        {/* <link href="https://fonts.cdnfonts.com/css/sofia-pro?styles=17634,17638" rel="stylesheet" /> */}
        {/* <link href="https://fonts.cdnfonts.com/css/sofia-pro" rel="stylesheet" /> */}
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
